[32m[I 2022-01-04 02:10:21,978][39m A new study created in memory with name: my_study
[33m[W 2022-01-04 02:10:22,014][39m Trial 0 failed because of the following error: AttributeError("'dict' object has no attribute 'samplerate'")
Traceback (most recent call last):
  File "/home/puppy/anaconda3/envs/bci/lib/python3.9/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "/tmp/ipykernel_90919/1176188093.py", line 16, in objective
    model = Tception(config.samplerate, config['filters']).to(device)
AttributeError: 'dict' object has no attribute 'samplerate'
/tmp/ipykernel_90919/1609232462.py:2: ExperimentalWarning: WeightsAndBiasesCallback is experimental (supported from v2.9.0). The interface can change in the future.
  wandbc = WeightsAndBiasesCallback(metric_name="5foldValidAccuracy", wandb_kwargs=wandb_kwargs)